import type { ContentfulStatusCode } from "hono/utils/http-status";
import { z } from "zod";

/**
 * RFC 9457 Problem Details for HTTP APIs
 * @see {@link https://www.rfc-editor.org/rfc/rfc9457.html RFC 9457 Problem Details for HTTP APIs}
 * @example
 * HTTP/1.1 403 Forbidden
 * Content-Type: application/problem+json
 * Content-Language: en
 *
 * {
 *  "type": "https://example.com/probs/out-of-credit",
 *  "title": "You do not have enough credit.",
 *  "detail": "Your current balance is 30, but that costs 50.",
 *  "instance": "/account/12345/msgs/abc",
 *  "balance": 30,
 *  "accounts": ["/account/12345", "/account/67890"]
 * }
 */
export const ProblemSchema = z.object({
  /**
   * A URI reference identifying the problem type.
   *
   * It is RECOMMENDED that absolute URIs be used in "type" when possible.
   *
   * When relative URIs are used, they include the full path (e.g., "/types/123").
   *
   * When "about:blank" is used, the title SHOULD be the same as the recommended HTTP status phrase for that code
   * (e.g., "Not Found" for 404, and so on),
   *
   * @default "about:blank"
   * @example "https://example.com/errors/validation"
   */
  type: z
    .string()
    .regex(/^[a-zA-Z][\w+.-]*:/, "Invalid URI")
    .default("about:blank")
    .optional(),

  /**
   * HTTP status code generated by the origin server.
   */
  status: z.custom<ContentfulStatusCode>(),

  /**
   * A short, human-readable summary of the problem.
   *
   * Not intended to be changed based on input.
   */
  title: z.string(),

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail: z.string().optional(),

  /**
   * A URI reference identifying the specific request instance.
   *
   * It is RECOMMENDED that absolute URIs be used in "instance" when possible.
   *
   * When relative URIs are used, they include the full path (e.g., "/instances/123").
   */
  instance: z.string().optional(),

  /**
   * Additional members that are specific to that problem type.
   */
  extensions: z.record(z.any(), z.any()).optional(),
});

/**
 * RFC 9457 Problem Details for HTTP APIs
 */
export type Problem = z.infer<typeof ProblemSchema>;

/**
 * Application-level error representing an RFC 9457 Problem Details response.
 */
export class ProblemError extends Error {
  /**
   * Structured RFC 9457 problem details associated with this error.
   */
  public readonly problem: Problem;

  constructor(options: Problem) {
    super(options.title);
    this.name = "ProblemError";
    this.problem = { ...options };
    this.problem.type = options.type ?? "about:blank";
  }
}
